language: node_js
node_js: node
services:
- mongodb
env:
  global:
    secure: azt36csBr0G3MMAPgebcXjARyefKSPt3iE8P/nTkgArpZfKK2aCpJuwqJJ5seFTGP/dL5+AzZTXgWudIDUK4NNGbZ0DYCy/E2OF8aY0FApzpM67tlU5E66jKBl4nxPi0JAa+ObLWTz8E/SI25sFr8xdHAmS7yjb2iPqWFKtfQ+KbujsIgtZT+Rb+2ixxqQX6yy2OmT6HDrCdzUGPNN5MDl09WPNFR5OgJHpwa1DbQ7T3VISd+elg9hAX7oCydEXHDsPGJQacq1w3IBzvEglbG66Gum9WIetKZAHOTquepQPJIs3Z5lg/juRTlClriQfH/eu8YcizCDvShxWkbn8vfAeHiTfozrFGWTIzNTAbK02+35VAZp5pYSwcVzxdJVht4nJSSMJboZtcmlctVCqLGZE1M0TlXUUYI9+7pPDsB2RJBiIYC+7d+Wyk0Zq9pgVe+3pb00wlb52PLr20u192L2P7CYa5eS4fT7dk7OfKt0g+iEgsDb1VdlNvqJMly+CYMZ6LXxxlRhp3r0IyJ5CbJ4OsZqhoCVOpJb+PEr3+zzfx+z6lFsKOcSqMC58OI6movGPR+rB65fgsNxAJG5hZNJRPIFnEuqHs1chGvILU5CEXkFXQMJLXRb0CFUj5sJvVUHubKKX+0mQX7tSagxqSGqfDuzByuTbVMVSfnQ5u6nA=
